function v = create_vehicle(iat, iatRandomValue, fuelType, refuelQuantity, refuelQuantityRandomValue)
    flowRate = 1;
    serviceDuration = refuelQuantity / flowRate;

    v = struct(...
        'iat', iat, ...
        'iatRandomValue', iatRandomValue, ...
        'fuelType', fuelType, ...
        'refuelQuantity', refuelQuantity, ...
        'refuelQuantityRandomValue', refuelQuantityRandomValue, ...
        'lane', -1, ...
        'pump', -1, ...
        'serviceDuration', serviceDuration, ...
        'arrivalTime', 0, ...
        'waitingDuration', 0, ...
        'initialLineNumber', 0);
end
