function v = create_vehicle(iat, fuelType, refuelQuantity)
    flowRate = 1;
    serviceDuration = refuelQuantity / flowRate;
    
    v = struct(...
        'iat', iat, ...
        'fuelType', fuelType, ...
        'refuelQuantity', refuelQuantity, ...
        'lane', -1, ...
        'pump', -1, ...
        'serviceDuration', serviceDuration, ...
        'arrivalTime', 0, ...
        'waitingDuration', 0, ...
        'initialLineNumber', 0);
end
